import pandas as pd

scoring_rules = {
    "STABILITÀ EMOTIVA – GESTIONE DELLE EMOZIONI": [
        {
            "id": "A1",
            "tag": "Il candidato sa controllare la reattività, l'impulsività quando prova emozioni e mantiene la capacità di comunicare in modo consapevole sia per i contenuti che per il tono",
            "description": "Il candidato sa controllare la reattività, l'impulsività quando prova emozioni e mantiene la capacità di comunicare in modo consapevole sia per i contenuti che per il tono",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato sa controllare la reattività, l'impulsività quando prova emozioni e mantiene la capacità di comunicare in modo consapevole sia per i contenuti che per il tono",
        },
        {
            "id": "A2",
            "tag": "Il candidato mantiene una relazione aperta anche dopo un disaccordo",
            "description": "Il candidato mantiene il rapporto con l'interlocutore nel corso della situazione di disaccordo o conflitto che ci sta raccontando, anche se ha discusso con lui ed ha opinioni diverse dalle sue. Questa regola é da individuare solo in una situazione di disaccordo o conflitto. Se non ci sono stati disaccordi o conflitti, questa regola é non trigger.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato mantiene il rapporto con l'interlocutore nel corso della situazione di disaccordo o conflitto che ci sta raccontando, anche se ha discusso con lui ed ha opinioni diverse dalle sue. Questa regola é da individuare solo in una situazione di disaccordo o conflitto. Se non ci sono stati disaccordi o conflitti, questa regola é non trigger.",
        },
        {
            "id": "A3",
            "tag": "Il candidato riflette sui feedback negativi per migliorare",
            "description": "A fronte di feedback negativi (per feedback si intende frase o discorso fatto a qualcuno per mettergli in evidenza un suo comportamento da modificare o competenze da far crescere o per comunicargli l'effetto che ció che ha detto o fatto ha avuto sugli altri) direttamente ricevuti o errori commessi, riflette, considera le informazioni ricevute per correggere durante la situazione il percorso verso il risultato",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "A fronte di feedback negativi (per feedback si intende frase o discorso fatto a qualcuno per mettergli in evidenza un suo comportamento da modificare o competenze da far crescere o per comunicargli l'effetto che ció che ha detto o fatto ha avuto sugli altri) direttamente ricevuti o errori commessi, riflette, considera le informazioni ricevute per correggere durante la situazione il percorso verso il risultato",
        },
        {
            "id": "A4",
            "tag": "Il candidato resta focalizzato e lucido sotto stress",
            "description": "Il candidato in situazioni di stress, ansia o paura resta focalizzato e agisce in maniera tangibile, lucidamente scegliendo cosa dire e cosa fare e agendo di conseguenza. Se il candidato mostra un intenzione la regola é non trigger, se invece racconta il comportamento agito lucidamente, la regola é true.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato in situazioni di stress, ansia o paura resta focalizzato e agisce in maniera tangibile, lucidamente scegliendo cosa dire e cosa fare e agendo di conseguenza. Se il candidato mostra un intenzione la regola é non trigger, se invece racconta il comportamento agito lucidamente, la regola é true.",
        },
        {
            "id": "A5",
            "tag": "Il candidato riconosce i momenti di forte emozione e prende pause",
            "description": "Il candidato riconosce i momenti in cui prova  emozioni forti che possono farlo agire in modo reattivo e non consapevole, o di quando è molto stanco  e dunque si ferma per prendere tempo, riposarsi o confrontarsi con altri prima di una decisione o un progetto importante. Se il candidato é molto stanco e ne é consapevole, si ferma e quindi la regola é true. Se perde luciditá o perde la calma e non si ferma, la regola é falsa. In tutti gli altri casi la regola é non trigger.",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato riconosce i momenti in cui prova  emozioni forti che possono farlo agire in modo reattivo e non consapevole, o di quando è molto stanco  e dunque si ferma per prendere tempo, riposarsi o confrontarsi con altri prima di una decisione o un progetto importante. Se il candidato é molto stanco e ne é consapevole, si ferma e quindi la regola é true. Se perde luciditá o perde la calma e non si ferma, la regola é falsa. In tutti gli altri casi la regola é non trigger.",
        },
        {
            "id": "A6",
            "tag": "Il candidato è consapevole dei possibili errori e valuta i rischi",
            "description": "Il candidato è consapevole della possibilità di commettere errori, valuta i rischi e agisce di conseguenza",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato è consapevole della possibilità di commettere errori, valuta i rischi e agisce di conseguenza.",
        },
        {
            "id": "A7",
            "tag": "Il candidato persevera di fronte alle difficoltà senza arrendersi",
            "description": "Il candidato di fronte alle difficoltà non rinuncia, si impegna ulteriormente, eventualmente chiede aiuto ma non rinuncia. Se la situazione presenta delle limitazioni legali impossibili da risolvere, la regola é non trigger.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Di fronte alle difficoltà, il candidato non si arrende, si impegna ulteriormente, eventualmente chiede aiuto ma non si arrende. Se la situazione presenta delle limitazioni legali impossibili da risolvere, la regola é non trigger.",
        },
        {
            "id": "A9",
            "tag": "Il candidato usa tecniche di rilassamento per gestire lo stress",
            "description": "Il candidato nelle situazioni di stress sa mettere in atto tecniche che lo rilassano e l'aiutano a restare focalizzato o centrato. La regola é true solo se il candidato racconta di aver messo in pratica queste tecniche. Se non racconta di aver messo in pratica queste tecniche, la regola é non trigger.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato nelle situazioni di stress sa mettere in atto tecniche che lo rilassano e l'aiutano a restare focalizzato o centrato. La regola é true solo se il candidato racconta di aver messo in pratica queste tecniche. Se non racconta di aver messo in pratica queste tecniche, la regola é non trigger.",
        },
        {
            "id": "A10",
            "tag": "Il candidato osserva gli aspetti positivi anche sotto pressione",
            "description": "Il candidato osserva gli aspetti positivi di se stesso o degli altri che sono stati messi in atto all'interno ed esclusivamente all'interno della situazione, senza giudicare chi fa parte della situazione stessa, quando è sotto pressione. In sintesi il candidato riesce a vedere il buono di una situazione anche se la stessa é estremamente stressante.Ignora le autovalutazioni del candidato quando decidi se questa regola é true, false o non trigger.",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato osserva gli aspetti positivi di se stesso o degli altri che sono stati messi in atto all'interno ed esclusivamente all'interno della situazione, senza giudicare chi fa parte della situazione stessa, quando è sotto pressione. In sintesi il candidato riesce a vedere il buono di una situazione anche se la stessa é estremamente stressante.Ignora le autovalutazioni del candidato quando decidi se questa regola é true, false o non trigger.",
        },
        {
            "id": "A10b",
            "tag": "Il candidato riconosce le cose positive fatte da sé e dagli altri",
            "description": "Il candidato riconosce le cose positive che sono state fatte da lui o da altri",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato riconosce le cose positive che sono state fatte da lui o da altri.",
        },
        {
            "id": "A11",
            "tag": "Il candidato affronta situazioni nuove con lucidità",
            "description": "Il candidato affronta lucidamente e/o senza cercare di evitarle e senza pregiudizi di alcun tipo, situazioni nuove e/o nelle quali non ha esperienza",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato affronta lucidamente e/o senza cercare di evitarle e senza pregiudizi di alcun tipo, situazioni nuove e/o nelle quali non ha esperienza",
        },
        {
            "id": "A13",
            "tag": "Il candidato impara dai comportamenti altrui riconoscendone il valore",
            "description": "Il candidato osserva le persone riconosce il valore di alcuni comportamenti e cerca di imparare a sua volta ad agire nello stesso modo. L'osservazione deve essere diretta all'interno della situazione che sta raccontando, per migliorare personalmente le proprie modalitá di agire. Se non viene raccontata esplicitamente l'osservazione di qualcun altro all'interno della situazione, la regola é non trigger.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato osserva le persone riconosce il valore di alcuni comportamenti e cerca di imparare a sua volta ad agire nello stesso modo. L'osservazione deve essere diretta all'interno della situazione che sta raccontando, per migliorare personalmente le proprie modalitá di agire. Se non viene raccontata esplicitamente l'osservazione di qualcun altro all'interno della situazione, la regola é non trigger.",
        },
    ],
    "LEADERSHIP E COMUNICAZIONE": [
        {
            "id": "B2",
            "tag": "Il candidato comunica apertamente le proprie emozioni",
            "description": "Il candidato è aperto nella comunicazione con l'altro rispetto alle sue emozioni quando é sotto pressione, arrabbiato o infastidito durante e solo durante la situazione raccontata.",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato è aperto nella comunicazione con l'altro rispetto alle sue emozioni quando é sotto pressione, arrabbiato o infastidito durante e solo durante la situazione raccontata.",
        },
        {
            "id": "B3",
            "tag": "Il candidato comunica in modo chiaro e accurato",
            "description": "Il candidato racconta in modo chiaro, narra fatti e riflessioni in modo chiaro e ricorda in modo accurato le situazioni che narra. Se la frase del candidato non é chiara, la regola é false. Questa regola puó presentarsi un infinito numero di volte.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato racconta in modo chiaro, narra fatti e riflessioni in modo chiaro e ricorda in modo accurato le situazioni che narra. Se la frase del candidato non é chiara, la regola é false. Questa regola puó presentarsi un infinito numero di volte.",
        },
        {
            "id": "B4",
            "tag": "Il candidato sa fare comunicazioni difficili anche con i superiori",
            "description": "Il candidato sa fare comunicazioni difficili anche con i superiori, quando ad esempio vuole esprimere un dissenso o portare alla luce temi che nessuno ha il coraggio di affrontare",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato sa fare comunicazioni difficili anche con i superiori, ad esempio quando vuole esprimere un dissenso o portare alla luce temi che nessuno ha il coraggio di affrontare.",
        },
        {
            "id": "B4a1",
            "tag": "Il candidato fa richieste dirette per miglioramenti",
            "description": "Il candidato fa richieste per se stesso o per il team che migliorino la qualità del lavoro o del benessere o delle relazioni o delle comunicazioni. E' diretto e non vive nell'aspettativa che le cose succedano. La regola é da considerarsi true o false solo se raccontata all'interno della situazione. In tutti gli altri casi la regola é non trigger.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato fa richieste per se stesso o per il team che migliorino la qualità del lavoro o del benessere o delle relazioni o delle comunicazioni. E' diretto e non vive nell'aspettativa che le cose succedano. La regola é da considerarsi true o false solo se raccontata all'interno della situazione. In tutti gli altri casi la regola é non trigger.",
        },
        {
            "id": "B4a",
            "tag": "Il candidato dà feedback negativi in modo costruttivo",
            "description": "Il candidato da feedback negativi in modo costruttivo all'interno della situazione raccontata. Se non esiste alcun feedback negativo all'interno della situazione raccontata, la regola é non trigger.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato da feedback negativi in modo costruttivo all'interno della situazione raccontata. Se non esiste alcun feedback negativo all'interno della situazione raccontata, la regola é non trigger.",
        },
        {
            "id": "B4h",
            "tag": "Il candidato dà feedback positivi e costruttivi orientati al futuro",
            "description": "Il candidato sa dare feed back positivi e costruttivi orientati al futuro riconoscendo le azioni positive fatte dagli altri",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato sa dare feedback positivi e costruttivi orientati al futuro, riconoscendo le azioni positive fatte dagli altri.",
        },
        {
            "id": "B4b",
            "tag": "Il candidato affronta i conflitti senza evitarli",
            "description": "Il candidato affronta il conflitto discutendo ed esprimendo il suo punto di vista divergente, senza cercare di evitarlo. La regola é true se il candidato esprime il suo punto di vista divergente, la regola é false se non viene affrontato il conflitto verbale malgrado ci siano i presupposti per farlo. In tutti gli altri casi la regola é non trigger.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato affronta il conflitto discutendo ed esprimendo il suo punto di vista divergente, senza cercare di evitarlo. La regola é true se il candidato esprime il suo punto di vista divergente, la regola é false se non viene affrontato il conflitto verbale malgrado ci siano i presupposti per farlo. In tutti gli altri casi la regola é non trigger.",
        },
        {
            "id": "B5",
            "tag": "Il candidato prepara le comunicazioni importanti in base agli interlocutori",
            "description": "Il candidato struttura e prepara le comunicazioni importanti tarandole in funzione degli interlocutori",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato struttura e prepara le comunicazioni importanti tarandole in funzione degli interlocutori.",
        },
        {
            "id": "B6",
            "tag": "Il candidato chiede chiarimenti su compiti e priorità",
            "description": "Il candidato fa domande e chiede specificazioni se non gli è chiaro il compito, i tempi di consegna, o il livello di priorità, di accuratezza richiesta eccetera",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato fa domande e chiede specificazioni se non gli è chiaro il compito, i tempi di consegna, o il livello di priorità, di accuratezza richiesta eccetera.",
        },
        {
            "id": "B7",
            "tag": "Il candidato è positivo sull'esito delle cose",
            "description": "Il candidato è positivo sull'esito delle cose. La regola é true se il candidato é positivo sull'esito della situazione raccontata, false se non lo é. In tutti gli altri casi la regola é non trigger.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato è positivo sull'esito delle cose.",
        },
        {
            "id": "B7bis",
            "tag": "Il candidato comunica positività agli altri",
            "description": "Il candidato è positivo sull'esito delle cose e lo comunica agli altri",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato è positivo sull'esito delle cose e lo comunica agli altri.",
        },
        {
            "id": "B8",
            "tag": "Il candidato si adatta alle diverse persone e situazioni",
            "description": "Il candidato adatta i propri comportamenti e la comunicazione alle diverse persone e situazioni e riesce a collaborare con persone molto diverse da sé e fra loro",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato adatta i propri comportamenti e la comunicazione alle diverse persone e situazioni e riesce a collaborare con persone molto diverse da sé e fra loro.",
        },
        {
            "id": "B9",
            "tag": "Il candidato mostra empatia anche sotto pressione",
            "description": "Il candidato sa mettersi nei panni degli altri, anche nei momenti di pressione, considera come gli altri si possono sentire a seguito delle scelte fatte o delle discussioni e lo considera nelle modalit di comunicazione che utilizza e nelle decisioni che prende",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato sa mettersi nei panni degli altri, anche nei momenti di pressione, considera come gli altri si possono sentire a seguito delle scelte fatte o delle discussioni e lo considera nelle modalità di comunicazione che utilizza e nelle decisioni che prende.",
        },
        {
            "id": "B10",
            "tag": "Il candidato resta lucido sotto stress e sceglie cosa dire e fare",
            "description": "Il candidato in situazioni di stress resta focalizzato e agisce lucidamente scegliendo cosa dire e cosa fare",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "In situazioni di stress, il candidato rimane concentrato e agisce lucidamente, scegliendo cosa dire e fare.",
        },
        {
            "id": "B11",
            "tag": "Il candidato cerca soluzioni alternative di fronte agli ostacoli",
            "description": "Il candidato a fronte di ostacoli cerca altre soluzioni, investe tempo ed energie per raggiungere obiettivi in modo alternativo",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Di fronte agli ostacoli, il candidato cerca altre soluzioni, investendo tempo ed energie per raggiungere gli obiettivi in modo alternativo.",
        },
        {
            "id": "B12",
            "tag": "Il candidato prende decisioni difficili per raggiungere l'obiettivo",
            "description": "Il candidato sa fare scelte difficili che sono sotto la sua responsabilità anche se possono scontentare gli altri e non essere condivise pur di raggiungere l'obiettivo",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato sa fare scelte difficili che sono sotto la sua responsabilità anche se possono scontentare gli altri e non essere condivise pur di raggiungere l'obiettivo.",
        },
        {
            "id": "G1",
            "tag": "Il candidato si assume le responsabilità e ammette gli errori",
            "description": "Il candidato si prende la responsabilità delle proprie azioni e in caso di errori commessi, lo ammette con i suoi interlocutori",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si prende la responsabilità delle proprie azioni e in caso di errori commessi, lo ammette con i suoi interlocutori.",
        },
        {
            "id": "G2",
            "tag": "Il candidato coinvolge le persone nei vari step del processo",
            "description": "Il candidato è attento a coinvolgere le persone nei vari step, comunicando, chiedendo il punto di vista, condividendo le criticità",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato è attento a coinvolgere le persone nei vari step, comunicando, chiedendo il punto di vista, condividendo le criticità.",
        },
        {
            "id": "G3",
            "tag": "Il candidato esprime il suo punto di vista anche se contrario al gruppo",
            "description": "Il candidato esprime il suo punto di vista anche se è scomodo o per qualche motivo difficile o contrario a quello del gruppo",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato esprime il suo punto di vista anche se è scomodo o per qualche motivo difficile o contrario a quello del gruppo.",
        },
        {
            "id": "G4",
            "tag": "Il candidato gestisce i progetti con ownership e prende decisioni",
            "description": "Il candidato gestisce il progetto con ownership e agisce e prende le decisioni che sono in suo potere per portarlo a compimento",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato gestisce il progetto con ownership e agisce e prende le decisioni che sono in suo potere per portarlo a compimento.",
        },
        {
            "id": "G4bis",
            "tag": "Il candidato propone miglioramenti anche al di fuori delle sue responsabilità",
            "description": "Il candidato se vede qualcosa che non funziona o potrebbe essere migliorato lo dice e fa di tutto per far si che le cose migliorino anche se non è sua diretta responsabilità",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Se il candidato vede qualcosa che non funziona o potrebbe essere migliorato, lo dice e fa di tutto per far sì che le cose migliorino anche se non è sua diretta responsabilità.",
        },
        {
            "id": "G5",
            "tag": "Il candidato crea un ambiente sicuro per gli errori dei collaboratori",
            "description": "Il candidato crea le condizioni affinchè le persone con cui collabora si sentano al sicuro e non attaccate in caso di errori commessi nel tentativo di arrivare all'obiettivo",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato crea le condizioni affinché le persone con cui collabora si sentano al sicuro e non attaccate in caso di errori commessi nel tentativo di raggiungere l'obiettivo.",
        },
        {
            "id": "G6",
            "tag": "Il candidato è consapevole dei rischi e agisce di conseguenza",
            "description": "Il candidato è consapevole della possibilità di commettere errori, valuta i rischi e agisce di conseguenza",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato è consapevole della possibilità di commettere errori, valuta i rischi e agisce di conseguenza.",
        },
        {
            "id": "G7",
            "tag": "Il candidato evita lamentele durante l'intervista",
            "description": "Il candidato se è scontento di qualche atteggiamento o comportamento di capi o colleghi, non si lamenta durante l'intervista con noi, ma rimane sulla descrizione dei fatti, comportamenti e riflessioni",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Se il candidato è scontento di qualche atteggiamento o comportamento di capi o colleghi, non si lamenta durante l'intervista con noi, ma rimane sulla descrizione dei fatti, comportamenti e riflessioni.",
        },
        {
            "id": "G8",
            "tag": "Il candidato fa richieste chiare per raggiungere l'obiettivo",
            "description": "Durante la situazione che racconta ha fatto richieste chiare agli interlocutori tese a raggiungere l'obiettivo e non a lamentarsi",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Durante la situazione che racconta, il candidato ha fatto richieste chiare agli interlocutori tese a raggiungere l'obiettivo e non a lamentarsi.",
        },
        {
            "id": "G9",
            "tag": "Il candidato riesce a influenzare le decisioni",
            "description": "Il candidato riesce a influenzare le decisioni",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato riesce a influenzare le decisioni.",
        },
        {
            "id": "G10",
            "tag": "Il candidato si assume la responsabilità della comunicazione in caso di incomprensioni",
            "description": "In caso di incomprensioni si prende la responsabilità del modo in cui ha comunicato",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "In caso di incomprensioni, il candidato si prende la responsabilità del modo in cui ha comunicato.",
        },
    ],
    "PEOPLE MANAGEMENT": [
        {
            "id": "C1",
            "tag": "Il candidato esprime fiducia e responsabilizza i collaboratori",
            "description": "Per essere 'true' il candidato deve raccontare il SUO comportamento durante la situazione che ci racconta e deve lui stesso esprimere fiducia e dare responsabilità ai collaboratori. La regola è 'false' se fa il contrario. In tutti gli altri casi, specialmente se il tag non è collegato all situazione raccontata, la regola è 'non trigger'.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Per essere 'true' il candidato deve raccontare il SUO comportamento durante la situazione che ci racconta e deve lui stesso esprimere fiducia e dare responsabilità ai collaboratori. La regola è 'false' se fa il contrario. In tutti gli altri casi, specialmente se il tag non è collegato all situazione raccontata, la regola è 'non trigger'.",
        },
        {
            "id": "C2",
            "tag": "Il candidato è attento al benessere del team e offre supporto",
            "description": "E' attento a come stanno le persone del suo team, chiede, ascolta e supporta nei momenti di difficoltà. La regola è 'true' se c'è un reale comportamento agito che attesta il tag. La regola è 'false' se il comportamento non attesta il tag. In tutti gli altri casi, specialmente se il tag non è collegato all situazione raccontata, la regola è 'non trigger'.",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "E' attento a come stanno le persone del suo team, chiede, ascolta e supporta nei momenti di difficoltà. La regola è 'true' se c'è un reale comportamento agito che attesta il tag. La regola è 'false' se il comportamento non attesta il tag. In tutti gli altri casi, specialmente se il tag non è collegato all situazione raccontata, la regola è 'non trigger'.",
        },
        {
            "id": "C3",
            "tag": "Il candidato stimola il ragionamento dei collaboratori con domande",
            "description": "Il candidato fa domande ai collaboratori per aiutarli a ragionare ed arrivare al loro punto di vista senza proporre subito la soluzione o la sua idea",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato fa domande ai collaboratori per aiutarli a ragionare ed arrivare al loro punto di vista senza proporre subito la soluzione o la sua idea.",
        },
        {
            "id": "C4",
            "tag": "Il candidato chiede il punto di vista dei collaboratori e ammette le proprie lacune",
            "description": "Il candidato chiede il punto di vista dei collaboratori, si confronta e se non sa qualcosa lo dice apertamente e chiede aiuto",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato chiede il punto di vista dei collaboratori, si confronta e se non sa qualcosa lo dice apertamente e chiede aiuto.",
        },
        {
            "id": "C5",
            "tag": "Il candidato celebra i successi e motiva il team",
            "description": "Il candidato celebra i successi e tiene alta la motivazione del suo team o dei peers",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato celebra i successi e tiene alta la motivazione del suo team o dei pari.",
        },
        {
            "id": "C6",
            "tag": "Il candidato delega e verifica la comprensione e l'allineamento",
            "description": "Il candidato delega e fa follow up per verificare che le persone abbiano compreso e sono allineate in qualità modalità e tempi",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato delega e fa follow up per verificare che le persone abbiano compreso e siano allineate in termini di qualità, modalità e tempi.",
        },
    ],
    "POTENZIALE": [
        {
            "id": "D1",
            "tag": "Il candidato ha chiarezza sui suoi obiettivi di vita e lavoro. Sa cosa é importante per sé, le prioritá, si comporta seguendo i valori in cui crede, sa fare scelte consapevoli rispetto ai suoi obiettivi.",
            "description": "Il candidato ha chiarezza sui suoi obiettivi nella vita e nel lavoro e sa cosa è importante per sé",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato ha chiarezza sui suoi obiettivi di vita e lavoro. Sa cosa é importante per sé, le prioritá, si comporta seguendo i valori in cui crede, sa fare scelte consapevoli rispetto ai suoi obiettivi.",
        },
        {
            "id": "D2",
            "tag": "Il candidato si impegna attivamente nella crescita personale",
            "description": "Il candidato si impegna nella sua crescita ed evoluzione cercando di modificare i suoi eventuali comportamenti non funzionali o per continuare a migliorare cio che gia fa bene. Si impegna e non solo dichiara, quindi ci racconta cosa sta facendo",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si impegna nella sua crescita ed evoluzione cercando di modificare i suoi eventuali comportamenti non funzionali o per continuare a migliorare ciò che già fa bene. Si impegna e non solo dichiara, quindi ci racconta cosa sta facendo.",
        },
        {
            "id": "D3",
            "tag": "Il candidato riflette su quanto avvenuto, mette piú aspetti in connessione fra loro prima di esprimere il suo punto di vista",
            "description": "Il candidato riflette prima di esprimere il suo punto di vista",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato riflette su quanto avvenuto, mette piú aspetti in connessione fra loro prima di esprimere il suo punto di vista",
        },
        {
            "id": "D4",
            "tag": "Il candidato ascolta criticamente le opinioni altrui per ampliare la propria prospettiva",
            "description": "Il candidato ascolta e riflette criticamente sulle opinioni espresse dagli altri per cogliere contributi o ampliare il suo punto di vista",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato ascolta e riflette criticamente sulle opinioni espresse dagli altri per cogliere contributi o ampliare il suo punto di vista.",
        },
        {
            "id": "D5",
            "tag": "Il candidato riflette sugli eventi passati, considera alternative e valuta i vantaggi. Per essere 'true' questa regola deve mostrare riflessione sugli eventi passati, considerazione di alternative e valutazione di vantaggi o motivazioni per prendere una decisione.",
            "description": "Il candidato dopo l'evento ripensa a come è andato e cosa avrebbe potuto fare di diverso ed ha consapevolezza del vantaggio che ci sarebbe stato",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato riflette sugli eventi passati, considera alternative e valuta i vantaggi. Per essere 'true' questa regola deve mostrare riflessione sugli eventi passati, considerazione di alternative e valutazione di vantaggi o motivazioni per prendere una decisione.",
        },
        {
            "id": "D6",
            "tag": "Il candidato accoglie i feedback con apertura lo ascolta e ci riflette",
            "description": "Il candidato accoglie i feedback e ascolta in modo aperto",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato accoglie i feedback con apertura lo ascolta e ci riflette",
        },
        {
            "id": "D6b",
            "tag": "Il candidato modifica il suo comportamento in base ai feedback se lo ritiene utile",
            "description": "Il candidato accoglie i feed back, ascolta, riflette e se lo ritiene utile, modifica il suo comportamento",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato modifica il suo comportamento in base ai feedback se lo ritiene utile",
        },
        {
            "id": "D6C",
            "tag": "Il candidato ricerca attivamente feedback dagli interlocutori che lo hanno potuto conoscere",
            "description": "Il candidato ricerca e chiede feedback ed identifica i corretti interlocutori per farlo",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato ricerca attivamente feedback dagli interlocutori che lo hanno potuto conoscere",
        },
        {
            "id": "D7",
            "tag": "Il candidato ammette gli errori durante l'intervista",
            "description": "Il candidato ammette gli errori durante l'intervista con noi",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato ammette gli errori durante l'intervista con noi.",
        },
        {
            "id": "D8",
            "tag": "Il candidato si é assunto le proprie responsabilità e ha ammesso i propri errori con gli interlocutori durante la situazione che ci racconta nell'intervista. Questa regola é 'true' solo se il candidato ha ammesso di aver sbagliato con gli interlocutori che aveva di fronte durante la situazione che ci racconta nell'intervista.",
            "description": "Il candidato si prende la responsabilità delle proprie azioni e in caso di errori commessi, lo ammette con i suoi interlocutori",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si é assunto le proprie responsabilità e ha ammesso i propri errori con gli interlocutori durante la situazione che ci racconta nell'intervista. Questa regola é 'true' solo se il candidato ha ammesso di aver sbagliato con gli interlocutori che aveva di fronte durante la situazione che ci racconta nell'intervista.",
        },
        {
            "id": "D9",
            "tag": "Il candidato apprende dalle esperienze per il futuro",
            "description": "Il candidato ci dichiara di aver appreso delle cose per il suo futuro grazie all'esperienza che ci ha raccontato",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato ci dichiara di aver appreso delle cose per il suo futuro grazie all'esperienza che ci ha raccontato.",
        },
        {
            "id": "D10",
            "tag": "Il candidato comunica in modo fluido. Per essere 'true' questa regola va applicata ad ogni frase e valutata singolarmente. Le frasi devono contenere riflessiono o racconti delle situazioni avvenute.",
            "description": "Il candidato racconta in modo fluido, narra fatti e riflessioni in modo chiaro e ricorda in modo accurato le situazioni che narra",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato comunica in modo fluido. Per essere 'true' questa regola va applicata ad ogni frase e valutata singolarmente. Le frasi devono contenere riflessiono o racconti delle situazioni avvenute.",
        },
        {
            "id": "D11b",
            "tag": "Il candidato valuta più opzioni",
            "description": "Il candidato valuta più opzioni prima di agire",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato valuta più opzioni prima di agire.",
        },
        {
            "id": "D12",
            "tag": "Il candidato è trasparente sulle proprie competenze: se sa di non essere adeguato a svolgere un compito, o di non sentirsi all'altezza, lo dichiara durante la situazione che ci racconta nell'intervista.",
            "description": "Il candidato è trasparente con gli altri rispetto alle proprie competenze e se non ha mai fatto una cosa oppure non ne ha le competenze, lo dichiara per non compromettere il successo del progetto affidatogli",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato è trasparente sulle proprie competenze: se sa di non essere adeguato a svolgere un compito, o di non sentirsi all'altezza, lo dichiara durante la situazione che ci racconta nell'intervista.",
        },
        {
            "id": "D13",
            "tag": "Il candidato trova soluzioni innovative",
            "description": "Il candidato trova il modo di fare ciò che non sa fare, da solo o chiedendo aiuto, ma almeno ci prova con impegno e sperimenta",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato trova il modo di fare ciò che non sa fare, da solo o chiedendo aiuto, ma almeno ci prova con impegno e sperimenta.",
        },
        {
            "id": "D14",
            "tag": "Il candidato ha fiducia nelle proprie capacità: l'aver fiducia nelle proprie capacitá lo spinge ad agire durante l'evento che ci racconta nell'intervista.",
            "description": "Il candidato crede nelle sue capacità di superare gli ostacoli",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato ha fiducia nelle proprie capacità: l'aver fiducia nelle proprie capacitá lo spinge ad agire durante l'evento che ci racconta nell'intervista.",
        },
        {
            "id": "D15",
            "tag": "Il candidato apprende dai feedback. Per essere 'true' il candidato deve aver imparato dal feedback che i suoi comportamenti necessitano di un cambiamento.",
            "description": "A fronte di feedback negativi o errori commessi, riflette e considera le informazioni ricevute per correggere il percorso verso il risultato",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato apprende dai feedback. Per essere 'true' il candidato deve aver imparato dal feedback che i suoi comportamenti necessitano di un cambiamento.",
        },
        {
            "id": "D16",
            "tag": "Il candidato risponde alle domande portando esempi concreti e comportamenti, senza divagare. Per essere 'true' questa regola va applicata ad ogni frase e valutata singolarmente.",
            "description": "Il candidato risponde alle domande portando esempi concreti e comportamenti, senza divagare. ",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato risponde alle domande portando esempi concreti e comportamenti, senza divagare. Per essere 'true' questa regola va applicata ad ogni frase e valutata singolarmente.",
        },
        {
            "id": "D17",
            "tag": "Il candidato dichiara di aver osservato gli altri e di aver acquisito nuovi comportamenti o riflessioni dall'osservazione. Questa regola va considerata solo se ci sono persone presenti da osservare nel contesto della situazione esposta. Per essere 'true' questa regola va applicata alla situazione che ci racconta nell'intervista: il candidato deve spiegare cosa ha imparato osservando una o piú persone con le quali si é relazionato durante la situazione che ci racconta nell'intervista. Se non ci sono persone da osservare, la regola é 'Non Trigger'.",
            "description": "Il candidato osserva lavorare gli altri per migliorarsi, per imparare a fare le cose nuove o farle meglio (non nella modalità di relazione o comportamentale ma nella parte tecnica)",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato dichiara di aver osservato gli altri e di aver acquisito nuovi comportamenti o riflessioni dall'osservazione. Questa regola va considerata solo se ci sono persone presenti da osservare nel contesto della situazione esposta. Per essere 'true' questa regola va applicata alla situazione che ci racconta nell'intervista: il candidato deve spiegare cosa ha imparato osservando una o piú persone con le quali si é relazionato durante la situazione che ci racconta nell'intervista. Se non ci sono persone da osservare, la regola é 'Non Trigger'.",
        },
        {
            "id": "D18",
            "tag": "Il candidato non riesce a ricordare una situazione che gli permetta di rispondere alla domanda",
            "description": "Al candidato non vengono in mente situazioni simili a quella richiesta anche dopo aver ripetuto la domanda",
            "true_score": -4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato non riesce a ricordare una situazione che gli permetta di rispondere alla domanda",
        },
        {
            "id": "D19",
            "tag": "Il candidato riflette sugli eventi passati",
            "description": "A valle dell'evento il candidato fa riflessioni su quanto accaduto e su cosa ha influito maggiormente sul risultato riflette, va attraverso le cose",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "A valle dell'evento, il candidato fa riflessioni su quanto accaduto e su cosa ha influito maggiormente sul risultato, riflette, va attraverso le cose.",
        },
    ],
    "RELAZIONE COLLABORAZIONE PIACEVOLEZZA ACCESSIBILITA": [
        {
            "id": "E1",
            "tag": "Il candidato è disponibile ad aiutare",
            "description": "Il candidato è disponibile ad aiutare e supportare gli altri",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato è disponibile ad aiutare e supportare gli altri.",
        },
        {
            "id": "E3",
            "tag": "Il candidato valorizza le opinioni altrui",
            "description": "Il candidato accoglie e valorizza gli interventi degli altri nelle discussioni anche se contrari alla sua opinione",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato accoglie e valorizza gli interventi degli altri nelle discussioni, anche se contrari alla sua opinione.",
        },
        {
            "id": "E4",
            "tag": "Il candidato si concentra sui fatti",
            "description": "Il candidato resta focalizzato sui fatti e non sul giudizio che ha degli altri, e/o di sé stesso",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato resta focalizzato sui fatti e non sul giudizio che ha degli altri, e/o di sé stesso.",
        },
        {
            "id": "E5",
            "tag": "Il candidato considera le conseguenze delle sue azioni",
            "description": "Il candidato considera le conseguenze che hanno sugli altri e sulle relazioni le scelte che propone e porta avanti",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato considera le conseguenze che le sue scelte hanno sugli altri e sulle relazioni, e le scelte che propone e porta avanti.",
        },
        {
            "id": "E6",
            "tag": "Il candidato cerca il compromesso",
            "description": "Quando c'è dissenso, il candidato propone alternative o modifica le proprie strategie per trovare un punto comune con gli altri e raggiungere gli obiettivi prefissati",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Quando c'è dissenso, il candidato propone alternative o modifica le proprie strategie per trovare un punto comune con gli altri e raggiungere gli obiettivi prefissati.",
        },
        {
            "id": "E7",
            "tag": "Il candidato si adatta alle diverse situazioni",
            "description": "Il candidato adatta i propri comportamenti e la comunicazione alle diverse persone e situazioni e riesce a collaborare con persone molto diverse da sé e fra loro",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato adatta i propri comportamenti e la comunicazione alle diverse persone e situazioni e riesce a collaborare con persone molto diverse da sé e fra loro.",
        },
        {
            "id": "E10b",
            "tag": "Il candidato ha fiducia nelle capacità altrui",
            "description": "Il candidato si fida delle risorse degli altri di superare gli ostacoli e glielo trasmette",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si fida delle risorse degli altri di superare gli ostacoli e glielo trasmette.",
        },
        {
            "id": "E11",
            "tag": "Il candidato mostra empatia",
            "description": "Il candidato sa mettersi nei panni degli altri, anche nei momenti di pressione, considera come gli altri si possono sentire a seguito delle scelte fatte o delle discussioni e lo considera nelle modalità di comunicazione che utilizza e nelle decisioni che prende",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato sa mettersi nei panni degli altri, anche nei momenti di pressione, considera come gli altri si possono sentire a seguito delle scelte fatte o delle discussioni e lo considera nelle modalità di comunicazione che utilizza e nelle decisioni che prende.",
        },
        {
            "id": "E12",
            "tag": "Il candidato chiede consigli relazionali",
            "description": "Il candidato se è in difficoltà, chiede consiglio su come risolvere temi relazionali",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Se il candidato è in difficoltà, chiede consiglio su come risolvere temi relazionali.",
        },
        {
            "id": "E13",
            "tag": "Il candidato coinvolge gli altri nelle decisioni",
            "description": "Il candidato coinvolge gli altri, si confronta, chiede opinioni quando deve fare scelte di business",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato coinvolge gli altri, si confronta, chiede opinioni quando deve fare scelte di business.",
        },
        {
            "id": "E14",
            "tag": "Il candidato mostra interesse per gli altri",
            "description": "Il candidato fa domande, si interessa a come stanno gli altri",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato fa domande, si interessa a come stanno gli altri.",
        },
        {
            "id": "E17",
            "tag": "Il candidato è consapevole del suo impatto",
            "description": "Il candidato è consapevole dell'impatto che ha sugli altri",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato è consapevole dell'impatto che ha sugli altri.",
        },
        {
            "id": "E18",
            "tag": "Il candidato è aperto al confronto",
            "description": "Il candidato cerca il confronto, è accessibile, è aperto",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato cerca il confronto, è accessibile, è aperto.",
        },
        {
            "id": "E19",
            "tag": "Il candidato mantiene le promesse",
            "description": "Il candidato si impegna a mantenere la parola data, le promesse fatte",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si impegna a mantenere la parola data, le promesse fatte.",
        },
        {
            "id": "E21",
            "tag": "Il candidato costruisce relazioni di fiducia",
            "description": "Il candidato si impegna a costruire relazioni di fiducia comunicando in modo trasparente e/o mantenendo la sua parola",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si impegna a costruire relazioni di fiducia comunicando in modo trasparente e/o mantenendo la sua parola.",
        },
        {
            "id": "E22",
            "tag": "Il candidato analizza i comportamenti altrui",
            "description": "Il candidato osserva i comportamenti degli altri e si fa domande su cosa li guida quali bisogni ci sono dietro certi comportamenti e agisce di conseguenza",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato osserva i comportamenti degli altri e si fa domande su cosa li guida, quali bisogni ci sono dietro certi comportamenti e agisce di conseguenza.",
        },
    ],
    "COSCIENZIOSITÀ- ORGANIZZAZIONE- STRUTTURAZIONE": [
        {
            "id": "F0",
            "tag": "Il candidato si prepara adeguatamente",
            "description": "Il candidato si prepara, studia per affrontare il task con competenza",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si prepara, studia per affrontare il compito con competenza.",
        },
        {
            "id": "F1",
            "tag": "Il candidato si focalizza sugli obiettivi aziendali",
            "description": "Il candidato agisce focalizzandosi sull'obiettivo da raggiungere nell'interesse dell'azienda",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato agisce focalizzandosi sull'obiettivo da raggiungere nell'interesse dell'azienda.",
        },
        {
            "id": "F1B",
            "tag": "Il candidato priorizza obiettivi personali",
            "description": "Il candidato agisce dando priorità ai suoi obiettivi personali mettendo in secondo piano quelli dell'azienda",
            "true_score": -4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato agisce dando priorità ai suoi obiettivi personali mettendo in secondo piano quelli dell'azienda.",
        },
        {
            "id": "F2",
            "tag": "Il candidato definisce le priorità",
            "description": "Il candidato definisce o ha chiarezza sulle priorità",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato definisce o ha chiarezza sulle priorità.",
        },
        {
            "id": "F3",
            "tag": "Il candidato rispetta le scadenze",
            "description": "Il candidato rispetta tempi di consegna e modalità concordate",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato rispetta tempi di consegna e modalità concordate.",
        },
        {
            "id": "F5",
            "tag": "Il candidato organizza efficientemente",
            "description": "Il candidato organizza efficientemente il tempo e le attività sue e/o degli altri",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato organizza efficientemente il tempo e le attività sue e/o degli altri.",
        },
        {
            "id": "F6",
            "tag": "Il candidato completa i progetti",
            "description": "Il candidato porta a termine i progetti",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato porta a termine i progetti.",
        },
        {
            "id": "F7",
            "tag": "Il candidato stabilisce alti standard",
            "description": "Il candidato setta alti standard qualitativi ed allinea le sue azioni agli standard",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato setta alti standard qualitativi ed allinea le sue azioni agli standard.",
        },
        {
            "id": "F8",
            "tag": "Il candidato anticipa i problemi",
            "description": "Il candidato anticipa i problemi, vede i problemi prima che si presentino",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato anticipa i problemi, vede i problemi prima che si presentino.",
        },
        {
            "id": "F9",
            "tag": "Il candidato cerca soluzioni alternative",
            "description": "Il candidato a fronte di ostacoli cerca altre soluzioni, investe tempo ed energie per raggiungere obiettivi in modo alternativo",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato a fronte di ostacoli cerca altre soluzioni, investe tempo ed energie per raggiungere obiettivi in modo alternativo.",
        },
        {
            "id": "F10",
            "tag": "Il candidato è resiliente",
            "description": "Il candidato a fronte di fallimenti si rialza e continua",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato a fronte di fallimenti si rialza e continua.",
        },
        {
            "id": "F12",
            "tag": "Il candidato definisce gli step per arrivare al risultato",
            "description": "Il candidato definisce gli step per arrivare al risultato",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato definisce gli step per arrivare al risultato.",
        },
        {
            "id": "F15",
            "tag": "Il candidato nel corso delle situazioni che racconta ha fornito dati che ha verificato, raccomandazioni affidabili,  di cui si sente sufficientemente sicuro",
            "description": "Il candidato nel corso delle situazioni che racconta ha fornito dati che ha verificato, raccomandazioni affidabili,  di cui si sente sufficientemente sicuro",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato nel corso delle situazioni che racconta ha fornito dati che ha verificato, raccomandazioni affidabili,  di cui si sente sufficientemente sicuro",
        },
        {
            "id": "F16",
            "tag": "Il candidato si attiva velocemente con senso di urgenza per mantenere la deadline ",
            "description": "Il candidato si attiva velocemente con senso di urgenza per mantenere la deadline ",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si attiva velocemente con senso di urgenza per mantenere la deadline ",
        },
        {
            "id": "F17",
            "tag": "Il candidato mentre procede verso l’obiettivo considera le nuove informazioni per verificare eventuali cambi di direzione",
            "description": "Il candidato mentre procede verso l’obiettivo considera le nuove informazioni per verificare eventuali cambi di direzione",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato mentre procede verso l’obiettivo considera le nuove informazioni per verificare eventuali cambi di direzione",
        },
        {
            "id": "F18",
            "tag": "Il candidato, se le azioni messe in atto non funzionano, cerca di capire cosa è andato storto per identificare cambi di direzione ",
            "description": "Il candidato, se le azioni messe in atto non funzionano, cerca di capire cosa è andato storto per identificare cambi di direzione",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato, se le azioni messe in atto non funzionano, cerca di capire cosa è andato storto per identificare cambi di direzione",
        },
        {
            "id": "F19",
            "tag": "Il candidato si impegna per raggiungere l’obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte",
            "description": "Il candidato si impegna per raggiungere l’obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si impegna per raggiungere l’obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte",
        },
        {
            "id": "F20",
            "tag": "Il candidato privilegia il raggiungimento del risultato nel rispetto dei tempi alla ricerca dell’eccellenza",
            "description": "Il candidato privilegia il raggiungimento del risultato nel rispetto dei tempi alla ricerca dell’eccellenza",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato privilegia il raggiungimento del risultato nel rispetto dei tempi alla ricerca dell’eccellenza",
        },
        {
            "id": "F21",
            "tag": "Il candidato privilegia l’accuratezza, la ricerca dell’eccellenza nel raggiungimento del task",
            "description": "Il candidato privilegia l’accuratezza, la ricerca dell’eccellenza nel raggiungimento del task",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato privilegia l’accuratezza, la ricerca dell’eccellenza nel raggiungimento del task",
        },
        {
            "id": "F22",
            "tag": "Il candidato si assicura che vengano fatte le cose in modo da evitare rischi",
            "description": "Il candidato si assicura che vengano fatte le cose in modo da evitare rischi",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si assicura che vengano fatte le cose in modo da evitare rischi",
        },
        {
            "id": "F23",
            "tag": "Il candidato racconta in modo fluido, narra fatti e riflessioni in modo chiaro e ricorda in modo accurato le situazioni che narra",
            "description": "Il candidato racconta in modo fluido, narra fatti e riflessioni in modo chiaro e ricorda in modo accurato le situazioni che narra",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato racconta in modo fluido, narra fatti e riflessioni in modo chiaro e ricorda in modo accurato le situazioni che narra",
        },
        {
            "id": "F24",
            "tag": "Il candidato si occupa del progetto affidatogli seguendo le regole e/o le richieste fatte dal manager o dall’azienda anche se non è d’accordo o emergono  difficoltà ",
            "description": "Il candidato si occupa del progetto affidatogli seguendo le regole e/o le richieste fatte dal manager o dall’azienda anche se non è d’accordo o emergono  difficoltà ",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si occupa del progetto affidatogli seguendo le regole e/o le richieste fatte dal manager o dall’azienda anche se non è d’accordo o emergono  difficoltà ",
        },
        {
            "id": "F25",
            "tag": "Il candidato tiene informate/informa  tutte le persone che devono conoscere lo stato del progetto",
            "description": "Il candidato tiene informate/informa  tutte le persone che devono conoscere lo stato del progetto",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato tiene informate/informa  tutte le persone che devono conoscere lo stato del progetto",
        },
    ],
    "PENSIERO ANALITICO": [
        {
            "id": "H1",
            "tag": "Il candidato riflette sull'essenza del problema e su come risolverlo",
            "description": "Il candidato riflette sull'essenza del problema e su come risolverlo",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato riflette sull'essenza del problema e su come risolverlo.",
        },
        {
            "id": "H3",
            "tag": "Il candidato va in profondità per comprendere e farsi una idea chiara",
            "description": "Il candidato va in profondità per comprendere e farsi una idea chiara e indaga, fa domande e va attraverso le cose",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato va in profondità per comprendere e farsi una idea chiara e indaga, fa domande e va attraverso le cose.",
        },
        {
            "id": "H5",
            "tag": "Il candidato analizza e quantifica, prende decisioni basate sui fatti",
            "description": "Il candidato analizza e quantifica, prende decisioni basate sui fatti",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato analizza e quantifica, prende decisioni basate sui fatti.",
        },
        {
            "id": "H6",
            "tag": "Il candidato ricorda e porta numeri e dati durante il racconto",
            "description": "Il candidato ricorda e porta numeri e dati durante il racconto",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato ricorda e porta numeri e dati durante il racconto.",
        },
    ],
    "PENSIERO STRATEGICO": [
        {
            "id": "I1",
            "tag": "Il candidato valuta più opzioni prima di prendere la decisione",
            "description": "Il candidato valuta più opzioni prima di prendere la decisione",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato valuta più opzioni prima di prendere la decisione.",
        },
        {
            "id": "I2",
            "tag": "Il candidato riesce a tenere in considerazione più elementi e a fare connessioni",
            "description": "Il candidato riesce a tenere in considerazione più elementi e a fare connessioni",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato riesce a tenere in considerazione più elementi e a fare connessioni.",
        },
        {
            "id": "I3",
            "tag": "Il candidato intuisce i problemi, li anticipa, li previene",
            "description": "Il candidato intuisce i problemi, li anticipa, li previene",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato intuisce i problemi, li anticipa, li previene.",
        },
    ],
    "FLESSIBILITÀ": [
        {
            "id": "L1",
            "tag": "Il candidato accetta nuove possibili soluzioni",
            "description": "Il candidato accetta nuove possibili soluzioni, è focalizzato sulla soluzione senza attaccamenti ai suoi punti di vista",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato accetta nuove possibili soluzioni, è focalizzato sulla soluzione senza attaccamenti ai suoi punti di vista.",
        },
        {
            "id": "L2",
            "tag": "Il candidato trova soluzioni alternative a fronte di ostacoli",
            "description": "Il candidato trova soluzioni alternative a fronte di ostacoli",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato trova soluzioni alternative a fronte di ostacoli.",
        },
        {
            "id": "L4",
            "tag": "Il candidato riesce a cambiare modalità di lavoro, riesce ad adattarsi",
            "description": "Il candidato riesce a cambiare modalità di lavoro, riesce ad adattarsi",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato riesce a cambiare modalità di lavoro, riesce ad adattarsi.",
        },
        {
            "id": "L5",
            "tag": "Il candidato si impegna per raggiungere l'obiettivo anche se è cambiato",
            "description": "Il candidato si impegna per raggiungere l'obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato si impegna per raggiungere l'obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte.",
        },
        {
            "id": "L6",
            "tag": "Il candidato adatta i propri comportamenti e la comunicazione",
            "description": "Il candidato adatta i propri comportamenti e la comunicazione alle diverse persone e situazioni e riesce a collaborare con persone molto diverse da sé e fra loro",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato adatta i propri comportamenti e la comunicazione alle diverse persone e situazioni e riesce a collaborare con persone molto diverse da sé e fra loro.",
        },
    ],
    "INNOVAZIONE CREATIVITA'": [
        {
            "id": "N2",
            "tag": "Il candidato propone o attua nuove modalità per fare le cose o risolvere problemi",
            "description": "Il candidato propone o attua nuove modalità per fare le cose o risolvere problemi, nuovi processi",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato propone o attua nuove modalità per fare le cose o risolvere problemi, nuovi processi.",
        },
        {
            "id": "N3",
            "tag": "Il candidato ricerca e identifica nuove possibilità, nuove idee",
            "description": "Il candidato ricerca e identifica nuove possibilità, nuove idee",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato ricerca e identifica nuove possibilità, nuove idee.",
        },
        {
            "id": "N4",
            "tag": "Il candidato fa connessioni inaspettate che portano a soluzioni innovative",
            "description": "Il candidato fa connessioni inaspettate che portano a soluzioni innovative o aprono nuovi punti di vista",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato fa connessioni inaspettate che portano a soluzioni innovative o aprono nuovi punti di vista.",
        },
    ],
    "ORIENTAMENTO AL CLIENTE": [
        {
            "id": "M1",
            "tag": "Il candidato risponde prontamente alle richieste dei clienti",
            "description": "Il candidato risponde prontamente alle richieste dei clienti",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato risponde prontamente alle richieste dei clienti.",
        },
        {
            "id": "M2",
            "tag": "Il candidato mostra interesse verso il cliente per le richieste fatte",
            "description": "Il candidato mostra interesse verso il cliente per le richieste fatte facendo domande e/o identificando nuove soluzioni da proporgli",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Il candidato mostra interesse verso il cliente per le richieste fatte facendo domande e/o identificando nuove soluzioni da proporgli.",
        },
        {
            "id": "M3",
            "tag": "Anticipa i bisogni del cliente con offerte interessanti e coinvolgenti",
            "description": "Anticipa i bisogni del cliente con offerte interessanti e coinvolgenti per il cliente",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Anticipa i bisogni del cliente con offerte interessanti e coinvolgenti per il cliente.",
        },
        {
            "id": "M4",
            "tag": "Ascolta i clienti e costruisce con loro relazioni di fiducia",
            "description": "Ascolta i clienti e costruisce con loro relazioni di fiducia tali da diventare per loro un punto di riferimento",
            "true_score": 4,
            "false_score": 0,
            "notrigger_score": 0,
            "trigger_condition": "Ascolta i clienti e costruisce con loro relazioni di fiducia tali da diventare per loro un punto di riferimento.",
        },
        {
            "id": "M5",
            "tag": "Si attiva per rispondere al meglio alle richieste del cliente",
            "description": "Si attiva per rispondere al meglio alle richieste del cliente anche se questo richiede un maggiore investimento di tempo ed energie da parte sua, magari oltre l'orario di lavoro",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Si attiva per rispondere al meglio alle richieste del cliente anche se questo richiede un maggiore investimento di tempo ed energie da parte sua, magari oltre l'orario di lavoro.",
        },
        {
            "id": "M6",
            "tag": "Si impegna con azioni concrete per costruire una relazione con il cliente",
            "description": "Si impegna con azioni concrete per costruire una relazione con il cliente, lo invita a venire in negozio, gli telefona personalmente, lo tiene aggiornato",
            "true_score": 2,
            "false_score": -2,
            "notrigger_score": 0,
            "trigger_condition": "Si impegna con azioni concrete per costruire una relazione con il cliente, lo invita a venire in negozio, gli telefona personalmente, lo tiene aggiornato.",
        },
    ],
}
