# Generated by Django 5.1.7 on 2025-05-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional details about the event', null=True)),
                ('start_date', models.DateField(help_text='Start date of the event')),
                ('end_date', models.DateField(blank=True, help_text='End date of the event (optional)', null=True)),
                ('is_full_day', models.BooleanField(default=True, help_text='Indicates if the event spans the entire day')),
                ('event_type', models.CharField(choices=[('REMINDER', 'Reminder')], default='REMINDER', help_text='Type of the event (holiday, meeting, etc.)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the event was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the event was last updated')),
            ],
        ),
    ]
