scoring_rules = {
    "COSCIENZIOSITÀ- ORGANIZZAZIONE- STRUTTURAZIONE": [
        {
            "id": "F0",
            "tag": "Il candidato si prepara adeguatamente",
            "description": "Il candidato si prepara, studia per affrontare il task con competenza",
            "trigger_condition": "Il candidato si prepara, studia per affrontare il compito con competenza.",
        },
        {
            "id": "F1",
            "tag": "Il candidato si focalizza sugli obiettivi aziendali",
            "description": "Il candidato agisce focalizzandosi sull'obiettivo da raggiungere nell'interesse dell'azienda",
            "trigger_condition": "Il candidato agisce focalizzandosi sull'obiettivo da raggiungere nell'interesse dell'azienda.",
        },
        {
            "id": "F1B",
            "tag": "Il candidato priorizza obiettivi personali",
            "description": "Il candidato agisce dando priorità ai suoi obiettivi personali mettendo in secondo piano quelli dell'azienda",
            "trigger_condition": "Il candidato agisce dando priorità ai suoi obiettivi personali mettendo in secondo piano quelli dell'azienda.",
        },
        {
            "id": "F2",
            "tag": "Il candidato definisce le priorità",
            "description": "Il candidato sa identificare i progetti o i problemi o gli obiettivi principali a cui dedicarsi come prima cosa. Se  non ha definito lui le priorità ha compreso da chi aveva la responsabilità di decidere, quali attività svolgere per prime",
            "trigger_condition": "Il candidato sa identificare i progetti o i problemi o gli obiettivi principali a cui dedicarsi come prima cosa. Se  non ha definito lui le priorità ha compreso da chi aveva la responsabilità di decidere, quali attività svolgere per prime",
        },
        {
            "id": "F3",
            "tag": "Il candidato rispetta le scadenze",
            "description": "il candidato è puntuale, rispetta i tempi concordati per concludere i progetti a lui assegnati.",
            "trigger_condition": "il candidato è puntuale, rispetta i tempi concordati per concludere i progetti a lui assegnati.",
        },
        {
            "id": "F5",
            "tag": "Il candidato organizza efficientemente",
            "description": "il candidato è organizzato e lo dimostra in quanto durante la situazione che ci racconta ha definito a chi affidare i compiti da svolgere e ha comunicato a  loro in quanto tempo devono essere fatti",
            "trigger_condition": " il candidato è organizzato e lo dimostra in quanto durante la situazione che ci racconta ha definito a chi affidare i compiti da svolgere e ha comunicato a  loro in quanto tempo devono essere fatti",
        },
        {
            "id": "F6",
            "tag": "Il candidato completa i progetti",
            "description": "Il candidato porta a termine i progetti",
            "trigger_condition": "Il candidato porta a termine i progetti.",
        },
        {
            "id": "F7",
            "tag": "Il candidato stabilisce alti standard",
            "description": "Il candidato setta alti standard qualitativi ed allinea le sue azioni agli standard",
            "trigger_condition": "Il candidato setta alti standard qualitativi ed allinea le sue azioni agli standard.",
        },
        {
            "id": "F8",
            "tag": "Il candidato anticipa i problemi",
            "description": "Il candidato anticipa i problemi, vede i problemi prima che si presentino",
            "trigger_condition": "Il candidato anticipa i problemi, vede i problemi prima che si presentino.",
        },
        {
            "id": "F9",
            "tag": "Il candidato cerca soluzioni alternative",
            "description": "Il candidato a fronte di ostacoli cerca altre soluzioni, investe tempo ed energie per raggiungere obiettivi in modo alternativo",
            "trigger_condition": "Il candidato a fronte di ostacoli cerca altre soluzioni, investe tempo ed energie per raggiungere obiettivi in modo alternativo.",
        },
        {
            "id": "F10",
            "tag": "Il candidato è resiliente",
            "description": "Il candidato non si lascia scoraggiare dal non raggiungimento di un obiettivo e continua a perseguire i suoi obiettivi con determinazione.Quando il candidato esprime un concetto di resilienza generale e non legato alla situazione che sta raccontando, la regola non é attivata. Riflessioni su come si sarebbe comportato dopo la situazione che racconta non sono da valutare.",
            "trigger_condition": "Il candidato non si lascia scoraggiare dal non raggiungimento di un obiettivo e continua a perseguire i suoi obiettivi con determinazione.Quando il candidato esprime un concetto di resilienza generale e non legato alla situazione che sta raccontando, la regola non é attivata. Riflessioni su come si sarebbe comportato dopo la situazione che racconta non sono da valutare.",
        },
        {
            "id": "F12",
            "tag": "Il candidato definisce gli step per arrivare al risultato",
            "description": "Il candidato definisce gli step per arrivare al risultato",
            "trigger_condition": "Il candidato definisce gli step per arrivare al risultato.",
        },
        {
            "id": "F15",
            "tag": "Il candidato nel corso delle situazioni che racconta ha fornito dati che ha verificato, raccomandazioni affidabili,  di cui si sente sufficientemente sicuro",
            "description": "Il candidato dimostra di essere una persona orientata ai dati, utilizzando fatti e numeri verificati per supportare le sue raccomandazioni, e mostra un ragionamento logico e affidabile nelle situazioni che racconta.",
            "trigger_condition": "Il candidato dimostra di essere una persona orientata ai dati, utilizzando fatti e numeri verificati per supportare le sue raccomandazioni, e mostra un ragionamento logico e affidabile nelle situazioni che racconta.",
        },
        {
            "id": "F16",
            "tag": "Il candidato si attiva velocemente con senso di urgenza per mantenere la deadline ",
            "description": "Il candidato si attiva velocemente con senso di urgenza per mantenere la deadline ",
            "trigger_condition": "Il candidato si attiva velocemente con senso di urgenza per mantenere la deadline ",
        },
        {
            "id": "F17",
            "tag": "Il candidato mentre procede verso l'obiettivo considera le nuove informazioni per verificare eventuali cambi di direzione",
            "description": "Il candidato mentre procede verso l'obiettivo considera le nuove informazioni per verificare eventuali cambi di direzione",
            "trigger_condition": "Il candidato mentre procede verso l'obiettivo considera le nuove informazioni per verificare eventuali cambi di direzione",
        },
         {
            "id": "F18",
            "tag": "Il candidato, se le azioni messe in atto non funzionano, cerca di capire cosa è andato storto per identificare cambi di direzione ",
            "description": "Il candidato, se le azioni messe in atto non funzionano, cerca di capire mentre la situazione si sta ancora compiendo cosa sta andando storto per identificare cambi di direzione. Le valutazioni e riflessioni a posteriori non vanno valutare",
            "trigger_condition": "Il candidato, se le azioni messe in atto non funzionano, cerca di capire mentre la situazione si sta ancora compiendo cosa sta andando storto per identificare cambi di direzione. Le valutazioni e riflessioni a posteriori non vanno valutare",
        },
        {
            "id": "F19",
            "tag": "Il candidato si impegna per raggiungere l'obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte",
            "description": "Il candidato si impegna per raggiungere l'obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte",
            "trigger_condition": "Il candidato si impegna per raggiungere l'obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte",
        },
        {
            "id": "F20",
            "tag": "Il candidato privilegia il raggiungimento del risultato nel rispetto dei tempi alla ricerca dell'eccellenza",
            "description": "Il candidato ha senso di urgenza ed è focalizzato sul raggiungimento del risultato nel rispetto dei tempi invece che sulla ricerca dell'eccellenza",
            "trigger_condition": "Il candidato ha senso di urgenza ed è focalizzato sul raggiungimento del risultato nel rispetto dei tempi invece che sulla ricerca dell'eccellenza",
        },
        {
            "id": "F21",
            "tag": "Il candidato privilegia l'accuratezza, la ricerca dell'eccellenza nel raggiungimento del task",
            "description": "Il candidato privilegia l'accuratezza, la ricerca dell'eccellenza nel raggiungimento del task",
            "trigger_condition": "Il candidato privilegia l'accuratezza, la ricerca dell'eccellenza nel raggiungimento del task",
        },
        {
            "id": "F22",
            "tag": "Il candidato si assicura che vengano fatte le cose in modo da evitare rischi",
            "description": "Il candidato si assicura che vengano fatte le cose in modo da evitare rischi. I rischi che il candidato vuole evitare devono essere esplicitati durante l’intervista",
            "trigger_condition": "Il candidato si assicura che vengano fatte le cose in modo da evitare rischi. I rischi che il candidato vuole evitare devono essere esplicitati durante l’intervista",
        },
        {
            "id": "F24",
            "tag": "Il candidato si occupa del progetto affidatogli seguendo le regole e/o le richieste fatte dal manager o dall'azienda anche se non è d'accordo o emergono  difficoltà ",
            "description": "Il candidato si occupa del progetto affidatogli seguendo le regole e/o le richieste fatte dal manager o dall'azienda anche se non è d'accordo o emergono  difficoltà ",
            "trigger_condition": "Il candidato si occupa del progetto affidatogli seguendo le regole e/o le richieste fatte dal manager o dall'azienda anche se non è d'accordo o emergono  difficoltà ",
        },
        {
            "id": "F25",
            "tag": "Il candidato tiene informate/informa  tutte le persone che devono conoscere lo stato del progetto",
            "description": "Il candidato tiene informate/informa  tutte le persone che devono conoscere lo stato del progetto",
            "trigger_condition": "Il candidato tiene informate/informa  tutte le persone che devono conoscere lo stato del progetto",
        },
    ],
}
