scoring_rules = {
    "POTENZIALE": [
        {
             "id": "D1",
            "tag": "Il candidato ha chiarezza sui suoi obiettivi di vita e lavoro. Sa cosa é importante per sé, le prioritá, si comporta seguendo i valori in cui crede, sa fare scelte consapevoli rispetto ai suoi obiettivi.",
            "description": "Il candidato dichiara cosa é importante per sé nella vita (anche al di fuori della sfera lavorativa), in termini di obiettivi che si prefigge di raggiungere. Racconta di compiere delle scelte allineate a questi obiettivi. Questo é ció che lo guida nelle scelte che ci racconta di aver fatto durante la situazione.",
            "trigger_condition": "Il candidato dichiara cosa é importante per sé nella vita (anche al di fuori della sfera lavorativa), in termini di obiettivi che si prefigge di raggiungere. Racconta di compiere delle scelte allineate a questi obiettivi. Questo é ció che lo guida nelle scelte che ci racconta di aver fatto durante la situazione.",
        },
        {
            "id": "D2",
            "tag": "Il candidato si impegna attivamente nella crescita personale",
            "description": "Il candidato si impegna nella sua crescita ed evoluzione cercando di modificare i suoi eventuali comportamenti non funzionali o per continuare a migliorare cio che gia fa bene. Si impegna e non solo dichiara, quindi ci racconta cosa sta facendo",
            "trigger_condition": "Il candidato si impegna nella sua crescita ed evoluzione cercando di modificare i suoi eventuali comportamenti non funzionali o per continuare a migliorare ciò che già fa bene. Si impegna e non solo dichiara, quindi ci racconta cosa sta facendo.",
        },
        {
              "id": "D3",
            "tag": "Il candidato riflette su quanto avvenuto, mette piú aspetti in connessione fra loro prima di esprimere il suo punto di vista",
            "description": "Il candidato racconta di aver riflettuto durante la situazione prima di esprimere la sua opinione durante la situazione. Le riflessioni a posteriori (ossia una volta che la situazione si é conclusa) e le azioni che ha compiuto non sono da valutare.",
            "trigger_condition": "Il candidato racconta di aver riflettuto durante la situazione prima di esprimere la sua opinione durante la situazione. Le riflessioni a posteriori (ossia una volta che la situazione si é conclusa) e le azioni che ha compiuto non sono da valutare.",
        },
        {
           
              "id": "D4",
            "tag": "Il candidato ascolta criticamente le opinioni altrui per ampliare la propria prospettiva",
            "description": "Il candidato ascolta le opinioni espresse dagli altri durante la situazione e ne tiene conto per ampliare o modificare il suo punto di vista. Le autoriflessioni e le opinioni espresse dagli altri a seguito di una richiesta di aiuto da parte del candidato non sono da valutare.",
            "trigger_condition": "Il candidato ascolta le opinioni espresse dagli altri durante la situazione e ne tiene conto per ampliare o modificare il suo punto di vista. Le autoriflessioni e le opinioni espresse dagli altri a seguito di una richiesta di aiuto da parte del candidato non sono da valutare.",
        },
        {
            "id": "D5",
            "tag": "Il candidato riflette sugli eventi passati, considera alternative e valuta i vantaggi. Per essere 'true' questa regola deve mostrare riflessione sugli eventi passati, considerazione di alternative e valutazione di vantaggi o motivazioni per prendere una decisione.",
            "description": "Il candidato dopo l'evento ripensa a come è andato e cosa avrebbe potuto fare di diverso ed ha consapevolezza del vantaggio che ci sarebbe stato",
            "trigger_condition": "Il candidato riflette sugli eventi passati, considera alternative e valuta i vantaggi. Per essere 'true' questa regola deve mostrare riflessione sugli eventi passati, considerazione di alternative e valutazione di vantaggi o motivazioni per prendere una decisione.",
        },
        {
           "id": "D6",
            "tag": "Il candidato accoglie i feedback con apertura lo ascolta e ci riflette",
            "description": "Il candidato SE RICEVE COMMENTI NEGATIVI é disponibile ad ascoltare i commenti negativi (per commenti negativi si intendono frasi o discorsi ricevuti da un'altra persona per mettere in evidenza un comportamento da modificare o competenze da far crescere o per comunicare l'effetto che ció che ha detto o fatto ha avuto sugli altri) ricevuti. Le autovalutazioni ed i commenti impliciti non devono essere valutati. SE NON C’É UN COMMENTO NEGATIVO ESPLICITO NEI CONFRONTI DEL CANDIDATO LA REGOLA É NON TRIGGER.",
            "trigger_condition": "Il candidato SE RICEVE COMMENTI NEGATIVI é disponibile ad ascoltare i commenti negativi (per commenti negativi si intendono frasi o discorsi ricevuti da un'altra persona per mettere in evidenza un comportamento da modificare o competenze da far crescere o per comunicare l'effetto che ció che ha detto o fatto ha avuto sugli altri) ricevuti. Le autovalutazioni ed i commenti impliciti non devono essere valutati. SE NON C’É UN COMMENTO NEGATIVO ESPLICITO NEI CONFRONTI DEL CANDIDATO LA REGOLA É NON TRIGGER.",
        },
        {
            "id": "D6b",
            "tag": "Il candidato modifica il suo comportamento in base ai feedback se lo ritiene utile",
            "description": "Il candidato SE RICEVE COMMENTI NEGATIVI é disponibile ad ascoltare i commenti negativi (per commenti negativi si intendono frasi o discorsi ricevuti da un'altra persona per mettere in evidenza un comportamento da modificare o competenze da far crescere o per comunicare l'effetto che ció che ha detto o fatto ha avuto sugli altri) ricevuti. Di conseguenza, elabora i commenti negativi ricevuti e, se lo ritiene utile, modifica il suo comportamento. Le autovalutazioni ed i commenti impliciti non devono essere valutati. SE NON C’É UN COMMENTO NEGATIVO ESPLICITO NEI CONFRONTI DEL CANDIDATO LA REGOLA É NON TRIGGER.",
            "trigger_condition": "Il candidato SE RICEVE COMMENTI NEGATIVI é disponibile ad ascoltare i commenti negativi (per commenti negativi si intendono frasi o discorsi ricevuti da un'altra persona per mettere in evidenza un comportamento da modificare o competenze da far crescere o per comunicare l'effetto che ció che ha detto o fatto ha avuto sugli altri) ricevuti. Di conseguenza, elabora i commenti negativi ricevuti e, se lo ritiene utile, modifica il suo comportamento. Le autovalutazioni ed i commenti impliciti non devono essere valutati. SE NON C’É UN COMMENTO NEGATIVO ESPLICITO NEI CONFRONTI DEL CANDIDATO LA REGOLA É NON TRIGGER.",
        },
        {
             "id": "D6C",
            "tag": "Il candidato ricerca attivamente feedback dagli interlocutori che lo hanno potuto conoscere",
            "description": "Il candidato chiede attivamente agli interlocutori commenti sul suo operato. I commenti ricevuti ma non richiesti dal candidato non devono essere valutati. Se il candidato non chiede commenti sul suo operato, la regola é non triggerata.",
            "trigger_condition": "Il candidato chiede attivamente agli interlocutori commenti sul suo operato. I commenti ricevuti ma non richiesti dal candidato non devono essere valutati. Se il candidato non chiede commenti sul suo operato, la regola é non triggerata.",
        },
        {
            "id": "D7",
            "tag": "Il candidato ammette gli errori durante l'intervista",
            "description": "Il candidato ammette gli errori durante l'intervista con noi",
            "trigger_condition": "Il candidato ammette gli errori durante l'intervista con noi.",
        },
        {
            "id": "D8",
            "tag": "Il candidato si é assunto le proprie responsabilità e ha ammesso i propri errori con gli interlocutori durante la situazione che ci racconta nell'intervista. Questa regola é 'true' solo se il candidato ha ammesso di aver sbagliato con gli interlocutori che aveva di fronte durante la situazione che ci racconta nell'intervista.",
            "description": "Il candidato si prende la responsabilità delle proprie azioni e in caso di errori commessi, lo ammette con i suoi interlocutori",
            "trigger_condition": "Il candidato si é assunto le proprie responsabilità e ha ammesso i propri errori con gli interlocutori durante la situazione che ci racconta nell'intervista. Questa regola é 'true' solo se il candidato ha ammesso di aver sbagliato con gli interlocutori che aveva di fronte durante la situazione che ci racconta nell'intervista.",
        },
        {
            "id": "D9",
            "tag": "Il candidato apprende dalle esperienze per il futuro",
            "description": "Il candidato ci dichiara di aver appreso delle cose per il suo futuro grazie all'esperienza che ci ha raccontato",
            "trigger_condition": "Il candidato ci dichiara di aver appreso delle cose per il suo futuro grazie all'esperienza che ci ha raccontato.",
        },
        {
             "id": "D11b",
            "tag": "Il candidato valuta più opzioni",
            "description": "Il candidato ha considerato e ci ha raccontato almeno un’alternativa alle sue azioni prima di agire. Le riflessioni a posteriori o implicite non sono da valutare.",
            "trigger_condition": "Il candidato ha considerato e ci ha raccontato almeno un’alternativa alle sue azioni prima di agire. Le riflessioni a posteriori o implicite non sono da valutare.",
        },
         {
        "id": "D12",
        "tag": "Il candidato è trasparente sulle proprie competenze: se sa di non essere adeguato a svolgere un compito, o di non sentirsi all'altezza, lo dichiara durante la situazione che ci racconta nell'intervista.",
            "description": "Il candidato è trasparente con gli altri rispetto alle proprie competenze e se non ha mai fatto una cosa oppure non ne ha le competenze, lo dichiara per non compromettere il successo del progetto affidatogli",
            "trigger_condition": "Il candidato è trasparente sulle proprie competenze: se sa di non essere adeguato a svolgere un compito, o di non sentirsi all'altezza, lo dichiara durante la situazione che ci racconta nell'intervista.",
        },
        {
            "id": "D13",
            "tag": "Il candidato trova soluzioni innovative",
            "description": "Il candidato si impegna per fare da solo o chiedendo aiuto ciò che non sa fare in situazioni nelle quali lui stesso non ha esperienza pregressa. Se non viene esplicitamente detto che la situazione é completamente nuova per il candidato, la regola é non trigger.",
            "trigger_condition": "Il candidato si impegna per fare da solo o chiedendo aiuto ciò che non sa fare in situazioni nelle quali lui stesso non ha esperienza pregressa. Se non viene esplicitamente detto che la situazione é completamente nuova per il candidato, la regola é non trigger.",
        },
        {
            "id": "D14",
            "tag": "Il candidato ha fiducia nelle proprie capacità: l'aver fiducia nelle proprie capacitá lo spinge ad agire durante l'evento che ci racconta nell'intervista.",
            "description": "Il candidato crede nelle sue capacità di superare gli ostacoli",
            "trigger_condition": "Il candidato ha fiducia nelle proprie capacità: l'aver fiducia nelle proprie capacitá lo spinge ad agire durante l'evento che ci racconta nell'intervista.",
        },
        {
            "id": "D15",
            "tag": "Il candidato apprende dai feedback. Per essere 'true' il candidato deve aver imparato dal feedback che i suoi comportamenti necessitano di un cambiamento.",
            "description": "Il candidato riceve commenti negativi (per commenti negativi si intendono frasi o discorsi ricevuti da un'altra persona per mettere in evidenza un comportamento da modificare o competenze da far crescere o per comunicare l'effetto che ció che ha detto o fatto ha avuto sugli altri) all’interno della situazione che ci sta raccontando. Di conseguenza, riflette e spiega le sue riflessioni, considera il commento/i commenti ricevuto/i per correggere durante la situazione il percorso verso il risultato. Le riflessioni su commenti ricevuti al di fuori della situazione non vanno considerate.I commenti impliciti non vanno considerati.",
            "trigger_condition": "Il candidato riceve commenti negativi (per commenti negativi si intendono frasi o discorsi ricevuti da un'altra persona per mettere in evidenza un comportamento da modificare o competenze da far crescere o per comunicare l'effetto che ció che ha detto o fatto ha avuto sugli altri) all’interno della situazione che ci sta raccontando. Di conseguenza, riflette e spiega le sue riflessioni, considera il commento/i commenti ricevuto/i per correggere durante la situazione il percorso verso il risultato. Le riflessioni su commenti ricevuti al di fuori della situazione non vanno considerate.I commenti impliciti non vanno considerati.",
        },   
         {
            "id": "D17",
            "tag": "Il candidato dichiara di aver osservato gli altri e di aver acquisito nuovi comportamenti o riflessioni dall'osservazione. Questa regola va considerata solo se ci sono persone presenti da osservare nel contesto della situazione esposta. Per essere 'true' questa regola va applicata alla situazione che ci racconta nell'intervista: il candidato deve spiegare cosa ha imparato osservando una o piú persone con le quali si é relazionato durante la situazione che ci racconta nell'intervista. Se non ci sono persone da osservare, la regola é 'Non Trigger'.",
            "description": "Il candidato osserva lavorare gli altri per migliorarsi, per imparare a fare le cose nuove o farle meglio (non nella modalità di relazione o comportamentale ma nella parte tecnica)",
            "trigger_condition": "Il candidato dichiara di aver osservato gli altri e di aver acquisito nuovi comportamenti o riflessioni dall'osservazione. Questa regola va considerata solo se ci sono persone presenti da osservare nel contesto della situazione esposta. Per essere 'true' questa regola va applicata alla situazione che ci racconta nell'intervista: il candidato deve spiegare cosa ha imparato osservando una o piú persone con le quali si é relazionato durante la situazione che ci racconta nell'intervista. Se non ci sono persone da osservare, la regola é 'Non Trigger'.",
        },
        {
            "id": "D18",
            "tag": "Il candidato non riesce a ricordare una situazione che gli permetta di rispondere alla domanda",
            "description": "Al candidato non vengono in mente situazioni simili a quella richiesta anche dopo aver ripetuto la domanda",
            "trigger_condition": "Il candidato non riesce a ricordare una situazione che gli permetta di rispondere alla domanda",
        },
        {
            "id": "D19",
            "tag": "Il candidato riflette sugli eventi passati",
            "description": "A valle dell'evento il candidato fa riflessioni sul perché é andata proprio in quel modo, riflettendo su cosa ha influito maggiormente sul risultato",
            "trigger_condition": "A valle dell'evento il candidato fa riflessioni sul perché é andata proprio in quel modo, riflettendo su cosa ha influito maggiormente sul risultato",
        },
    ],
    "PENSIERO STRATEGICO": [
        {
            "id": "I1",
            "tag": "Il candidato valuta più opzioni prima di prendere la decisione",
            "description": "Il candidato valuta piu opzioni prima di prendere la decisione rispetto alla  situazione che ci racconta, ha quindi considerato più possibilità di agire",
            "trigger_condition": "Il candidato valuta piu opzioni prima di prendere la decisione rispetto alla  situazione che ci racconta, ha quindi considerato più possibilità di agire",
        },
        {
            "id": "I2",
            "tag": "Il candidato riesce a tenere in considerazione più elementi e a fare connessioni",
            "description": "Il candidato riesce a tenere in considerazione più elementi e a fare connessioni",
            "trigger_condition": "Il candidato riesce a tenere in considerazione più elementi e a fare connessioni.",
        },
        {
            "id": "I3",
            "tag": "Il candidato intuisce i problemi, li anticipa, li previene",
            "description": "Il candidato sa intuire i problemi prima che si verifichino e si attiva con un piano d’azione per prevenirli",
            "trigger_condition": "Il candidato sa intuire i problemi prima che si verifichino e si attiva con un piano d’azione per prevenirli",
        },
    ],
    "FLESSIBILITÀ": [
        {
            "id": "L1",
            "tag": "Il candidato accetta nuove possibili soluzioni",
            "description": "Il candidato accetta nuove possibili soluzioni, è focalizzato sulla soluzione senza attaccamenti ai suoi punti di vista",
            "trigger_condition": "Il candidato accetta nuove possibili soluzioni, è focalizzato sulla soluzione senza attaccamenti ai suoi punti di vista.",
        },
        {
            "id": "L2",
            "tag": "Il candidato trova soluzioni alternative a fronte di ostacoli",
            "description": "Il candidato trova soluzioni alternative a fronte di ostacoli",
            "trigger_condition": "Il candidato trova soluzioni alternative a fronte di ostacoli.",
        },
        {
            "id": "L4",
            "tag": "Il candidato riesce a cambiare modalità di lavoro, riesce ad adattarsi",
            "description": "Il candidato riesce a cambiare modalità di lavoro quando realizza che non stanno funzionando, e riesce ad adattare le modalitá di lavoro",
            "trigger_condition": "Il candidato riesce a cambiare modalità di lavoro quando realizza che non stanno funzionando, e riesce ad adattare le modalitá di lavoro",
        },
        {
            "id": "L5",
            "tag": "Il candidato si impegna per raggiungere l'obiettivo anche se è cambiato",
            "description": "Il candidato si impegna per raggiungere l'obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte",
            "trigger_condition": "Il candidato si impegna per raggiungere l'obiettivo anche se è cambiato e anche se le modalità di lavoro non sono quelle da lui proposte.",
        },
        {
            "id": "L6",
            "tag": "Il candidato adatta i propri comportamenti e la comunicazione",
            "description": "Il candidato modifica i propri comportamenti e la comunicazione che utilizza in funzione delle diverse persone e situazioni per collaborare in modo positivo con persone diverse da sé.",
            "trigger_condition": "Il candidato modifica i propri comportamenti e la comunicazione che utilizza in funzione delle diverse persone e situazioni per collaborare in modo positivo con persone diverse da sé.",
        },
    ],
}
