scoring_rules = {
    "RELAZIONE COLLABORAZIONE PIACEVOLEZZA ACCESSIBILITA": [
        {
            "id": "E1",
            "tag": "Il candidato è disponibile ad aiutare",
            "description": "Il candidato è disponibile ad aiutare e supportare gli altri",
            "trigger_condition": "Il candidato è disponibile ad aiutare e supportare gli altri.",
        },
        {
            "id": "E3",
            "tag": "Il candidato valorizza le opinioni altrui",
            "description": "Il candidato ascolta senza contrastare e valorizza gli interventi degli altri",
            "trigger_condition": "Il candidato ascolta senza contrastare e valorizza gli interventi degli altri",
        },
        {
            "id": "E4",
            "tag": "Il candidato si concentra sui fatti",
            "description": "Il candidato, nel prendere le decisioni o nei confronti con gli altri, non si fa influenzare dai giudizi che ha su di sé o sugli altri ed è focalizzato su fatti concreti",
            "trigger_condition": "Il candidato, nel prendere le decisioni o nei confronti con gli altri, non si fa influenzare dai giudizi che ha su di sé o sugli altri ed è focalizzato su fatti concreti",
        },
        {
            "id": "E5",
            "tag": "Il candidato considera le conseguenze delle sue azioni",
            "description": "Il candidato quando propone o prende delle decisioni è consapevole delle conseguenze emotive e relazionali delle persone coinvolte",
            "trigger_condition": "Il candidato quando propone o prende delle decisioni è consapevole delle conseguenze emotive e relazionali delle persone coinvolte",
        },
        {
            "id": "E6",
            "tag": "Il candidato cerca il compromesso",
            "description": "Quando ci sono opinioni diverse in un gruppo, il candidato propone nuove idee che tengono conto del punto di vista di piú persone.",
            "trigger_condition": "Quando ci sono opinioni diverse in un gruppo, il candidato propone nuove idee che tengono conto del punto di vista di piú persone.",
        },
        {
            "id": "E7",
            "tag": "Il candidato si adatta alle diverse situazioni",
            "description": "Il candidato adatta i propri comportamenti e la comunicazione alle diverse persone e situazioni e riesce a collaborare con persone molto diverse da sé e fra loro",
            "trigger_condition": "Il candidato adatta i propri comportamenti e la comunicazione alle diverse persone e situazioni e riesce a collaborare con persone molto diverse da sé e fra loro.",
        },
        {
            "id": "E10b",
            "tag": "Il candidato ha fiducia nelle capacità altrui",
            "description": "Ha fiducia nel fatto che gli altri sapranno superare gli ostacoli e glielo comunica (è incoraggiante)",
            "trigger_condition": "Ha fiducia nel fatto che gli altri sapranno superare gli ostacoli e glielo comunica (è incoraggiante)",
        },
        {
            "id": "E11",
            "tag": "Il candidato mostra empatia",
            "description": "Il candidato constata le emozioni degli interlocutori presenti nella situazione che ci sta raccontando e le considera per definire come comporarsi successivamente nella situazione che ci sta raccontando.",
            "trigger_condition": "Il candidato constata le emozioni degli interlocutori presenti nella situazione che ci sta raccontando e le considera per definire come comporarsi successivamente nella situazione che ci sta raccontando",
        },
        {
            "id": "E12",
            "tag": "Il candidato chiede consigli relazionali",
            "description": "Il candidato se è in difficoltà, chiede consiglio su come risolvere temi relazionali",
            "trigger_condition": "Se il candidato è in difficoltà, chiede consiglio su come risolvere temi relazionali.",
        },
        {
            "id": "E13",
            "tag": "Il candidato coinvolge gli altri nelle decisioni",
            "description": "Il candidato coinvolge gli altri, si confronta, chiede opinioni quando deve fare scelte di business",
            "trigger_condition": "Il candidato coinvolge gli altri, si confronta, chiede opinioni quando deve fare scelte di business.",
        },
        {
            "id": "E14",
            "tag": "Il candidato mostra interesse per gli altri",
            "description": "Il candidato chiede agli altri come stanno",
            "trigger_condition": "Il candidato chiede agli altri come stanno",
        },
        {
            "id": "E17",
            "tag": "Il candidato è consapevole del suo impatto",
            "description": "Il candidato è consapevole dell’effetto emotivo che i suoi comportamenti o le sue parole hanno sugli altri",
            "trigger_condition": "Il candidato è consapevole dell’effetto emotivo che i suoi comportamenti o le sue parole hanno sugli altri",
        },
        {
            "id": "E18",
            "tag": "Il candidato è aperto al confronto",
            "description": "Il candidato cerca il confronto, è accessibile, è aperto",
            "trigger_condition": "Il candidato cerca il confronto, è accessibile, è aperto.",
        },
        {
            "id": "E19",
            "tag": "Il candidato mantiene le promesse",
            "description": "Il candidato si impegna a mantenere gli impegni presi",
            "trigger_condition": "Il candidato si impegna a mantenere gli impegni presi",
        },
        {
            "id": "E21",
            "tag": "Il candidato costruisce relazioni di fiducia",
            "description": "Il candidato si impegna a costruire relazioni di fiducia comunicando in modo trasparente e/o mantenendo la sua parola",
            "trigger_condition": "Il candidato si impegna a costruire relazioni di fiducia comunicando in modo trasparente e/o mantenendo la sua parola.",
        },
        {
            "id": "E22",
            "tag": "Il candidato analizza i comportamenti altrui",
            "description": "Il candidato osserva i comportamenti degli altri e si fa domande su cosa li guida quali bisogni ci sono dietro certi comportamenti e agisce di conseguenza",
            "trigger_condition": "Il candidato osserva i comportamenti degli altri e si fa domande su cosa li guida, quali bisogni ci sono dietro certi comportamenti e agisce di conseguenza.",
        },
    ],
}
