# Generated by Django 5.1.7 on 2025-05-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['index']},
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='documents_d_chunk_i_b4d0ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='document_chunk_embedding_idx',
        ),
        migrations.RenameField(
            model_name='documentchunk',
            old_name='chunk_index',
            new_name='index',
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['index'], name='documents_d_index_8d8506_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['embedding'], name='document_chunk_embedding_idx'),
        ),
    ]
