# Generated by Django 5.1.7 on 2025-05-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentchunk_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='document_chunk_embedding_idx',
        ),
    ]
