# Generated by Django 5.1.7 on 2025-05-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_vector_extension'),
        ('documents', '0003_remove_documentchunk_document_chunk_embedding_idx'),
    ]

    operations = [
    ]
