# Generated by Django 5.1.7 on 2025-05-10 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pgvector'),
        ('documents', '0004_merge_20250510_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttask',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentcontent',
            name='drive_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_content', to='api.drivefile'),
        ),
    ]
